script to update tornado dataset
IN-CORE/dev-scripts pull request #32
Opened 2024-01-16 17:51 UTC by Rashmil-1999

This script will help in modifying mongodb for hazardDatasets field

2024-01-17 20:22 UTC, longshuicy requested changes
Nice script!

2024-01-17 20:22 UTC, longshuicy commented on incore-services/tornado_hazardDataset.ipynb
> +    "### SHIT!!! revertttttt\n",
AHAHHA i appreciate the passion but you might want to remove the cuss word :p

2024-01-17 20:22 UTC, longshuicy commented on incore-services/tornado_hazardDataset.ipynb
> +    "        document[\"hazardDataset\"] = document[\"rasterDataset\"]\n",
Have we decided to make it hazardDatasets and an array?

2024-01-17 20:30 UTC, Rashmil-1999 commented on incore-services/tornado_hazardDataset.ipynb
> +    "### SHIT!!! revertttttt\n",
:(

2024-01-17 20:31 UTC, Rashmil-1999 commented on incore-services/tornado_hazardDataset.ipynb
> +    "        document[\"hazardDataset\"] = document[\"rasterDataset\"]\n",
I don't think so but I think Chris mentioned today on slack it would be a good idea to make it so...

2024-01-23 19:59 UTC, longshuicy commented
You might want to remove this cell 
<img width="376" alt="image" src="https://github.com/IN-CORE/dev-scripts/assets/13950475/9fae2a72-a5a7-46a8-9bc8-7bf9fa3dce35">

2024-01-23 20:39 UTC, closed without merging