SLC retrofit cost input data generation
IN-CORE/dev-scripts pull request #42
Opened 2024-02-26 18:52 UTC by ywkim312

@longshuicy I included input csv files in the PR. Should I remove those and only include the outputs? Also, the pyincore-datawolf repo was in Chris' personal space. Should we move this to that repo still?

2024-02-27 15:31 UTC, longshuicy requested changes
Could you clean the static cost table `Salt_Lake_City_Build_W_Cost.csv` to only keep "guid", "struct_typ" and "cost" and save that version in the data. 

Then you don't need to do that as a part of the script 
```
# keep only necessary columns
    cost_df = cost_df[['guid', 'struct_typ', 'Retrofit_Cost']]
  ```

2024-02-27 15:31 UTC, longshuicy commented on retrofit-cost-scripts/slc/data/Salt_Lake_City_Build_W_Cost_output.json
> +    "structure_types": [
On a second thought maybe we should remove this section
- since it's not related to cost
- we get the derived information from the unique keys in the `total_cost_by_buildilng_type` section

2024-02-27 15:31 UTC, longshuicy commented on retrofit-cost-scripts/slc/data/Salt_Lake_City_Build_W_Cost_output.json
> +    "total_cost_by_struct_type": [
"total_cost_by_buildilng_type"

2024-02-27 15:31 UTC, longshuicy commented on retrofit-cost-scripts/slc/data/Salt_Lake_City_Build_W_Cost_output.json
> +    "total_count_by_struct_type": [
Sorry on a second thought this is not related the cost, maybe we should leave it out

2024-02-27 15:31 UTC, longshuicy commented on retrofit-cost-scripts/slc/data/Salt_Lake_City_Build_W_Cost_output.json
> +    ]
Is it possible to add `total_cost_by_retrofit_method` section as well?  You can get the unique value of that from the retrofit plan file; For example, SLC there is only one method `Wood or Metal Deck Diaphragms Retrofitted`

2024-02-27 15:43 UTC, ywkim312 commented on retrofit-cost-scripts/slc/data/Salt_Lake_City_Build_W_Cost_output.json
> +    ]
Retrofit plan file is not being used at all in this code. So to do that, I have to include it in the code. Do you still want to do that? If so, I will make it.

2024-02-27 15:44 UTC, ywkim312 commented
> Could you clean the static cost table `Salt_Lake_City_Build_W_Cost.csv` to only keep "guid", "struct_typ" and "cost" and save that version in the data.
> 
> Then you don't need to do that as a part of the script
> 
> ```
> # keep only necessary columns
>     cost_df = cost_df[['guid', 'struct_typ', 'Retrofit_Cost']]
> ```

Isn't this more dynamic? If we want to use the similar process later, doing this will save some manual work?

2024-02-27 15:50 UTC, longshuicy commented on retrofit-cost-scripts/slc/data/Salt_Lake_City_Build_W_Cost_output.json
> +    ]
wait then what total cost are you generating?

2024-02-27 15:51 UTC, longshuicy commented
> > Could you clean the static cost table `Salt_Lake_City_Build_W_Cost.csv` to only keep "guid", "struct_typ" and "cost" and save that version in the data.
> > Then you don't need to do that as a part of the script
> > ```
> > # keep only necessary columns
> >     cost_df = cost_df[['guid', 'struct_typ', 'Retrofit_Cost']]
> > ```
> 
> Isn't this more dynamic? If we want to use the similar process later, doing this will save some manual work?

Ok sounds good.

2024-02-27 22:24 UTC, ywkim312 commented on retrofit-cost-scripts/slc/data/Salt_Lake_City_Build_W_Cost_output.json
> +    ]
This will not be in the output json but the code is there. If you need to include, just simply uncomment the lines

2024-02-27 22:24 UTC, ywkim312 commented on retrofit-cost-scripts/slc/data/Salt_Lake_City_Build_W_Cost_output.json
> +    "total_count_by_struct_type": [
Commented out

2024-02-27 22:25 UTC, ywkim312 commented on retrofit-cost-scripts/slc/data/Salt_Lake_City_Build_W_Cost_output.json
> +    "total_cost_by_struct_type": [
renamed but commented out to only keep the total cost

2024-02-27 22:26 UTC, ywkim312 commented on retrofit-cost-scripts/slc/data/Salt_Lake_City_Build_W_Cost_output.json
> +    "structure_types": [
commented out.

2024-02-27 22:26 UTC, ywkim312 commented
@longshuicy I added the lines to use retrofit_plan. It is coming from the data service by providing the dataset id

2024-02-27 23:23 UTC, longshuicy commented on retrofit-cost-scripts/slc/slc_retrofit_cost.py
> +    cost_df = cost_df.dropna(subset=['Retrofit_Cost'])
can we keep those as NA?

2024-02-27 23:24 UTC, longshuicy commented on retrofit-cost-scripts/slc/slc_retrofit_cost.py
> +        cost_df = cost_df[['guid', 'struct_typ', 'retrofit_key', 'Retrofit_Cost']]
The output only needs "guid", "retrofit_cost" two columns

2024-02-28 02:09 UTC, ywkim312 commented on retrofit-cost-scripts/slc/slc_retrofit_cost.py
> +        cost_df = cost_df[['guid', 'struct_typ', 'retrofit_key', 'Retrofit_Cost']]
the output only has guid and retrofit two columns. This is not the output yet.

2024-02-28 02:21 UTC, ywkim312 commented on retrofit-cost-scripts/slc/slc_retrofit_cost.py
> +    cost_df = cost_df.dropna(subset=['Retrofit_Cost'])
changed to keep as NA

2024-02-28 05:25 UTC, longshuicy approved these changes

2024-02-28 05:25 UTC, merged