script to sync user
IN-CORE/dev-scripts pull request #9
Opened 2022-12-14 19:34 UTC by longshuicy

script to 
- prepopoulate roles and step 
- read keycloak group to list all the users
- sync those user with each maestro services

Need to get keycloak admin username and password to test

2022-12-14 19:40 UTC, robkooper commented on incore-services/sync_users_roles_steps_playbook.py
> +def get_userinfo_from_keycloa_group(group_id, keycloak_base_url, admin_username, admin_password):
typo

2022-12-14 19:41 UTC, robkooper commented on incore-services/sync_users_roles_steps_playbook.py
> +import json
can this be moved to incore-platform since we already have a sync script
can we add a dockerfile so it can run in the cluster

2022-12-14 19:42 UTC, robkooper commented on incore-services/sync_users_roles_steps_playbook.py
> +    userinfo_url = keycloak_base_url + "/admin/realms/In-core/users?exact=true"
can `In-core` be a variable, so it can be changed if we want

2022-12-14 19:43 UTC, robkooper commented on incore-services/sync_users_roles_steps_playbook.py
> +    userinfo_url = keycloak_base_url + "/admin/realms/In-core/groups/{0}/members".format(group_id)
can In-core be a variable, so it can be changed if we want

2022-12-14 19:43 UTC, robkooper commented on incore-services/sync_users_roles_steps_playbook.py
> +    keycloak_base_url = "https://incore-dev.ncsa.illinois.edu/auth"
can this be os.getenv()

2022-12-14 19:43 UTC, robkooper commented on incore-services/sync_users_roles_steps_playbook.py
> +            "group_id": "18ec08f4-86ae-4ec3-bb57-54c19e5398cf"  # get this informatio from keycloak
```suggestion
            "group_id": "18ec08f4-86ae-4ec3-bb57-54c19e5398cf"  # get this information from keycloak
```

2022-12-14 19:44 UTC, robkooper commented on incore-services/sync_users_roles_steps_playbook.py
> +            "group_id": "c098e80e-64a0-43b0-91b2-66a79dadb225"  # get this informatio from keycloak
```suggestion
            "group_id": "c098e80e-64a0-43b0-91b2-66a79dadb225"  # get this information from keycloak
```

2022-12-14 19:44 UTC, robkooper commented on incore-services/sync_users_roles_steps_playbook.py
> +            "group_id": "2b691eaf-22ff-41ea-b8f5-d835a4a9e35a"  # get this informatio from keycloak
```suggestion
            "group_id": "2b691eaf-22ff-41ea-b8f5-d835a4a9e35a"  # get this information from keycloak
```

2022-12-14 19:45 UTC, robkooper commented on incore-services/sync_users_roles_steps_playbook.py
> +def get_userinfo_from_keycloa_group(group_id, keycloak_base_url, admin_username, admin_password):
```suggestion
def get_userinfo_from_keycloak_group(group_id, keycloak_base_url, admin_username, admin_password):
```

2022-12-14 19:46 UTC, robkooper commented on incore-services/sync_users_roles_steps_playbook.py
> +    keycloak_base_url = "https://incore-dev.ncsa.illinois.edu/auth"
maybe have a server_url so it can be used in the config section.

2022-12-14 19:46 UTC, robkooper requested changes
left a bunch of comments

2022-12-14 20:02 UTC, longshuicy commented on incore-services/sync_users_roles_steps_playbook.py
> +    userinfo_url = keycloak_base_url + "/admin/realms/In-core/users?exact=true"
done

2022-12-14 20:04 UTC, longshuicy commented on incore-services/sync_users_roles_steps_playbook.py
> +import json
is incore-platform a repo? 
This might only need to run once for preparing the coming workshop though, not quite a long term solution yet

2022-12-14 20:07 UTC, robkooper commented on incore-services/sync_users_roles_steps_playbook.py
> +import json
https://github.com/IN-CORE/platform

2022-12-16 18:13 UTC, ywkim312 approved these changes

2022-12-16 23:16 UTC, longshuicy commented
> 

addressed most except moving the incore-platform since this script only needs to run once (not quite ready for every 15 mintues)

2022-12-16 23:19 UTC, merged